# Generated by Django 2.2.5 on 2019-09-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dancer_name',
            new_name='ddr_name'
        ),
        migrations.AlterField(
            model_name='student',
            name='ddr_name',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='discord_id',
            field=models.CharField(blank=True, help_text='discord username and discriminator (eg: tropikiko#7800)', max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='pic_url',
            field=models.URLField(verbose_name='submission picture url'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='submission time'),
        ),
    ]
