# Generated by Django 2.2.5 on 2019-09-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_rename_ddr_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('week', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
