# Generated by Django 2.2.5 on 2019-09-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='submissions.Challenge'),
            preserve_default=False,
        ),
    ]
