# Generated by Django 2.2.5 on 2019-09-20 23:01

from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_challenge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'get_latest_by': 'week'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(default=submissions.models.Challenge.latest_week, on_delete=django.db.models.deletion.PROTECT, to='submissions.Challenge'),
        ),
    ]
