# Generated by Django 3.2.5 on 2021-07-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_challenge_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('JV', 'Junior Varsity'), ('FR', 'Freshman'), ('VA', 'Varsity'), ('GR', 'Graduate'), ('', 'Unknown')], default='', max_length=2, verbose_name='division'),
        ),
    ]
