# Generated by Django 3.2.5 on 2021-07-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='alum',
        ),
    ]
