# Generated by Django 3.2.5 on 2021-07-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_remove_student_alum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='discord_id',
            new_name='discord_name',
        ),
    ]
