# Generated by Django 3.2.5 on 2021-07-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_rename_discord_id_student_discord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discord_snowflake_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
