# Generated by Django 3.2.5 on 2021-07-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_student_discord_snowflake_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
