# Generated by Django 3.2.5 on 2021-07-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_challenge_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='level',
            field=models.CharField(choices=[('JV', 'Junior Varsity'), ('FR', 'Freshman'), ('VA', 'Varsity'), ('GR', 'Graduate'), ('', 'Unknown')], default='', max_length=2, verbose_name='division'),
        ),
    ]
