# Generated by Django 3.2.5 on 2021-07-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_submission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('JV', 'Junior Varsity'), ('FR', 'Freshman'), ('VA', 'Varsity'), ('GR', 'Graduate'), ('', 'Unknown')], default='', max_length=2, verbose_name='division (most recent)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='level',
            field=models.CharField(choices=[('JV', 'Junior Varsity'), ('FR', 'Freshman'), ('VA', 'Varsity'), ('GR', 'Graduate'), ('', 'Unknown')], default='', max_length=2, verbose_name='division (at submission time)'),
        ),
    ]
